<a href="https://colab.research.google.com/github/keerthanarangaraju/data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_1=[[1,2,3],[4,5,6],[7,8,9]]
sample_mat=np.array(list_1)

In [ ]:
sample_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:


np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
np.arange(18)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(10,int)

NameError: ignored

In [ ]:
import numpy as np

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(1,2)

array([[0.38844443, 0.87130123]])

In [ ]:
np.random.randn(1,2)

array([[ 1.01098759, -2.31718147]])

In [ ]:
np.random.randint(1,10)

6

In [ ]:
np.random.randint(1,10,8)

array([7, 2, 3, 4, 6, 2, 3, 7])

In [ ]:
sample_arr=np.arange(20)

In [ ]:
sample_arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
rand_arr=np.random.randint(0,10,9)
rand_arr

array([1, 1, 3, 8, 3, 7, 6, 9, 3])

In [ ]:
rand_arr.reshape(3,3)

array([[1, 1, 3],
       [8, 3, 7],
       [6, 9, 3]])

In [ ]:
rand_arr.min()

1

In [ ]:
rand_arr.argmin()

0

In [ ]:
rand_arr.dtype

dtype('int64')

In [ ]:
a.T

In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
sample_arr[3:7]

array([3, 4, 5, 6])

In [ ]:
sample_arr[3:7]=17
sample_arr

array([ 0,  1,  2, 17, 17, 17, 17,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
sample_arr[:]=19
sample_arr

array([19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19])

In [ ]:
sample_max=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
sample_max[0:2,2]

array([3, 6])

In [ ]:
sample_max[0:3,2]

array([3, 6, 9])

In [ ]:
sample_max[:,1]

array([2, 5, 8])

In [ ]:
sample_max1=sample_max[:,(0,1,2)]
sample_max1+sample_max

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

np.exp(sample_max)

np.sqrt(sample_max)

In [ ]:
np.max(sample_max)

9

In [ ]:
np.min(sample_max)

1

In [ ]:
np.log(sample_max)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.argmin(sample_max)

0

In [ ]:
np.argmax(sample_max)

8

np.square(sample_max)

In [ ]:
np.std(sample_max)

2.581988897471611

In [ ]:
np.mean(sample_max)

5.0

In [ ]:

arr1=np.random.randn(3,4)

In [ ]:
np.round(arr1,decimals=3)

array([[ 0.255, -0.335, -2.599,  0.415],
       [-0.981, -1.459,  1.369,  0.857],
       [-0.451,  0.398, -0.47 ,  0.43 ]])

In [ ]:
arr2=np.array([1,1,2,3,4])
np.unique(arr2)

array([1, 2, 3, 4])